name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-11

    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: SwiftLint
      run: ./swiftlint.sh
      env:
        BASE_BRANCH: ${{ github.base_ref }}

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
