name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Check out repository and submodules
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: SwiftLint (only changed files)
      uses: norio-nomura/action-swiftlint@3.2.1
      env:
        DIFF_BASE: ${{ github.base_ref }}

    - name: Build
      run: swift build -v

    - name: Run tests
      run: swift test -v
